  name: Despliegue continuo a QA
  on:
    push:
      branches:
        - 'hotfix/*'
        - 'release/*'
  jobs:
    setup-build:
      name: Configurar, Construir
      runs-on: ubuntu-latest
      env:
        PROJECT_ID: "saludantofagasta-proy1"
        KEY: ${{ secrets.GCP_KEY }}
        API_ZONE: "us-east4-a"
        API_CLUSTER: "cluster-qa"
        API_KEY: ${{ secrets.API_KEY }}
        MONGO_IP: ${{ secrets.MONGO_IP_QA }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Build Test
          env:
            #Variables usadas solo para la ejecución de las pruebas
            MONGO_URI: "mongodb://localhost:27017/hrapp_dev"
            PORT: "3000"
            HOST_NAME: "localhost"
            JWT_SECRET: "TEST"
          run: |
            chmod +x ./gradlew
            ./gradlew helmInstallApiConfiguracionToCloud