  name: Despliegue continuo a QA
  on:
    push:
      branches:
        - 'hotfix/*'
        - 'release/*'
  jobs:
    setup-build:
      name: Configurar, Construir
      runs-on: ubuntu-latest
      env:
        PROJECT_ID: ${{ secrets.CGP_PROJECT }}
        KEY: ${{ secrets.GCP_KEY }}
        API_ZONE: ${{ secrets.GCP_ZONE_QA }}
        API_CLUSTER: ${{ secrets.GCP_CLUSTER_QA }}
        API_KEY: ${{ secrets.API_KEY }}
        MONGO_IP: ${{ secrets.MONGO_IP_QA }}
      steps:
        - name: Checkout
          uses: actions/checkout@2

        - name: Build Test
          env:
            #Variables usadas solo para la ejecución de las pruebas
            MONGO_URI: "mongodb://localhost:27017/hrapp_dev"
            PORT: "3000"
            HOST_NAME: "localhost"
            JWT_SECRET: "TEST"
          run: |
            printf $KEY > key.json
            chmod +x ./gradlew
            ./gradlew helmInstallApiConfiguracionToCloud --no-deamon