  name: Despliegue continuo a QA
  on:
    push:
      branches:
        - 'release/*'
  jobs:
    setup-build:
      name: Configurar, Construir
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@2